source 'https://rubygems.org'


gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'react-rails'
gem 'devise'



group :development, :test do
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'awesome_print'
  gem 'faker'

  gem 'web-console', '~> 2.0'
end

