source 'https://rubygems.org'


gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'react-rails'
gem 'devise'


# Use Unicorn as the app server
# gem 'unicorn'
gem 'faker'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :test, :development  do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'factory_girl_rails'
end


group :development, :test do
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'awesome_print'

  gem 'web-console', '~> 2.0'
end

group :test do
  gem 'shoulda-matchers', require: false
  gem 'shoulda'
end

